exec-once = hypridle
exec-once = swaync
exec-once = waybar
exec-once = fcitx5 --disable notificationitem
exec-once = awww-daemon
exec-once = swayosd-server
exec-once = hyprpolkitagent

# Slow app launch fix -- set systemd vars
exec-once = systemctl --user import-environment $(env | cut -d'=' -f 1)
exec-once = dbus-update-activation-environment --systemd --all

exec-once = hyprctl setcursor sunset-cursors 24
exec-once = openrgb -p red
